services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: ./frontend
  #   command: yarn start
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
