# Generated by Django 5.0.7 on 2024-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videoSource', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
