# Generated by Django 5.1 on 2024-08-26 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_userviewhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserViewHistory',
            new_name='WatchHistory',
        ),
    ]
