# Generated by Django 5.0.7 on 2024-07-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='caption',
        ),
    ]
