# Generated by Django 5.0.7 on 2024-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_title_video_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
